Add failing onupdate on abstract model.
The test 'test_onupdate' would try to trigger the onchange on the 'user.name'
and  fail with:

   psycopg2.ProgrammingError: relation "text_onupdate_mixin" does not exist
   ERROR tdb_cb235a4f3 odoo.addons.test_xoeuf_api.tests.test_api: ` LINE 1: SELECT "text_onupdate_mixin".id FROM "text_onupdate_mixin" W...

Because the table of the abstract model doesn't have a table.