Don't proxy module-level attributes to the underlying model.
This fixes the tests failures we're seeing in xopgi.base'
test_time_related_mixins:

Traceback (most recent call last):
  File "src/merchise/pgi2/xhg2/sources/dists/xopgi.base/xopgi/test_time_related_mixins/tests/test_timespan_mixin.py", line 97, in test_create4
    def test_create4(self, end):
  File ".local/share/virtualenvs/xhg2-FNO8VUjs/lib/python3.5/site-packages/hypothesis/core.py", line 986, in wrapped_test
    had_seed=wrapped_test._hypothesis_internal_use_seed
  File ".local/share/virtualenvs/xhg2-FNO8VUjs/lib/python3.5/site-packages/hypothesis/core.py", line 498, in __init__
    warn=escalate_warning,
  File ".local/share/virtualenvs/xhg2-FNO8VUjs/lib/python3.5/site-packages/coverage/collector.py", line 107, in __init__
    self.origin = short_stack()
  File ".local/share/virtualenvs/xhg2-FNO8VUjs/lib/python3.5/site-packages/coverage/debug.py", line 143, in short_stack
    stack = inspect.stack()[limit:skip:-1]
  File ".pyenv/versions/3.5.5/lib/python3.5/inspect.py", line 1470, in stack
    return getouterframes(sys._getframe(1), context)
  File ".pyenv/versions/3.5.5/lib/python3.5/inspect.py", line 1447, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File ".pyenv/versions/3.5.5/lib/python3.5/inspect.py", line 1421, in getframeinfo
    lines, lnum = findsource(frame)
  File ".pyenv/versions/3.5.5/lib/python3.5/inspect.py", line 761, in findsource
    module = getmodule(object, file)
  File ".pyenv/versions/3.5.5/lib/python3.5/inspect.py", line 714, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File ".local/share/virtualenvs/xhg2-FNO8VUjs/lib/python3.5/site-packages/xoeuf/models/_proxy.py", line 103, in __getattr__
    'likely due to an invalid call site.' % attr
RuntimeError: Cannot find attribute '__file__' in proxy model. This is most likely due to an invalid call site.